### ISSUE TITLE
Tiger Tank missing from the roster

### ISSUE THREAD

**Issue by swittenberger** [BSData/world-of-tanks-miniatures-game#1]
I noticed there is no Tiger Tank information, even though we have the data card for it in the rulebook. Could we add it please? (If not, I'd be willing to do it if you can post a tutorial on how to read/use these files :P )

**Comment by swittenberger** [comment]
Tried adding the data manually myself, but the UIDs are killing me and I'm getting a null pointer exception most likely because of that.

`Details:

java.lang.NullPointerException
	at net.battlescribe.a.c.a(BattleScribe:275)
	at net.battlescribe.a.a.a(BattleScribe:686)
	at net.battlescribe.a.a.b(BattleScribe:1556)
	at net.battlescribe.a.a.a(BattleScribe:1488)
	at net.battlescribe.desktop.common.ManageDataWindowController$c.a(BattleScribe:296)
	at net.battlescribe.desktop.common.ManageDataWindowController$c.call(BattleScribe:294)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

The stats are the following:
Points: 65
Tier 7
Special Rule: Fortress (When this tank is the target of a Side shot, do not substract a defense die)
Firepower 5
Survivability 2
Mobility 2
Initiative 4
Hit Points 8
Commander/Gunner/Driver/RadioOperator/Loader available
Heavy Tank: When Defending, this tank may reroll a blank defence die.

**Comment by swittenberger** [comment]
Found out we have an editor. Did the edits myself and exported it to a .catz file. :) Hope it helps anyone else who might need it.
[Platoon.zip](https://github.com/BSData/world-of-tanks-miniatures-game/files/6078908/Platoon.zip)

**Comment by WastelandGS** [comment]
I'll be sticking to the official releases for the time being, but as above, it should be pretty straightforward to add it to your own local data files. Thanks
